set-option -g prefix C-b

set -g history-limit 10000

# set first window to index 1 (not 0) to map more to the keyboard layout
set -g base-index 1
set -g pane-base-index 1

# pass through xterm keys
set -g xterm-keys on

# Redraw the client (if interrupted by wall, etc)
bind R refresh-client

# reload tmux config with ctrl + a + r
 unbind r
 bind r \
     source-file ~/.tmux.conf \;\
         display 'Reloaded tmux config.'


# Ctrl - w or w to kill panes
unbind w
unbind C-w
bind-key w kill-pane
bind-key C-w kill-pane

# Using the mouse to switch panes
set -g mouse on

set-option -g allow-rename off
set -g default-terminal "xterm-256color"

# Visual Activity Monitoring between windows
setw -g monitor-activity on
set -g visual-activity on

# Show tmux positions in titles
set -g set-titles on

# Copy from tmux to system clipboard
# Needs xclip -> sudo apt install xclip
#bind -t vi-copy y copy-pipe "xclip -sel clip -i"

set -g status-left-style bg=black,fg=white
set -g status-right-style bg=white,fg=black

set -g status-left " #S "
set -g status-right "%l:%M %p %D "

set -g window-status-format " #I: #W "
set -g window-status-current-format " #I: #W "
set -g window-status-current-style bg=white,fg=black
set -g status-style bg=black,fg=white
