export LS_COLORS=gxBxhxDxfxhxhxhxhxcxcx

setopt PROMPT_SUBST
export PROMPT='%F{green}%t%f %F{blue}%~%f %F{red}${vcs_info_msg_0_}%f$ '

alias ll="ls -alFh --color=auto"
alias la="ls -A --color=auto"
alias l="ll"
alias c="cd $CODE_LOCATION"
alias gs="git status"
alias gb='git branch'
alias dt="cd $DESKTOP"

if command -v fzf &> /dev/null
then
    source <(fzf --zsh)
fi

export EDITOR='vim'
if command -v nvim &> /dev/null
then
    export EDITOR="nvim"
    alias vim='nvim'
    alias vi='nvim'
fi

autoload edit-command-line
zle -N edit-command-line
bindkey '^X^e' edit-command-line

autoload -U select-word-style
select-word-style bash

HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

bindkey -e 
export CLICOLOR=1

